<? $record=array (
  0 => 
  array (
    0 => 'cFg*^',
    1 => '16',
    2 => 'Riga',
    3 => 'KumARI',
    4 => 'ir',
    5 => '00-24',
    6 => 'nav',
    7 => 'cFg^',
    8 => 'pending',
  ),
  1 => 
  array (
    0 => 'Nixon',
    1 => '17',
    2 => 'Kuldīga',
    3 => 'Click.tm, G.mode vēl daži bijuši!',
    4 => 'ir',
    5 => 'apm. 14.oo - kamēr miegs nāk! ',
    6 => 'santiims3',
    7 => 'Nixon_',
    8 => 'pending',
  ),
  2 => 
  array (
    0 => 'kplo vai Kipello',
    1 => '18',
    2 => 'Jelgava',
    3 => 'BRILLIANT , Brug3er\'s',
    4 => 'ir',
    5 => 'briivdienas gadas visa diena darbadinas tikai peec 7 lidz kadiem 11',
    6 => 'kipiskipis',
    7 => 'kplo',
    8 => 'pending',
  ),
  3 => 
  array (
    0 => 'RebeL',
    1 => '14 gadi',
    2 => 'Ragana',
    3 => 'es speleeju visu laiku bez team bet esmu bijis vienaa klanaa [cs.ime.lv] ta sbija servera klans bet es itkaa bez kalna bet sagribejaas tiimu! ;)',
    4 => 'ir',
    5 => '11.00 - 01.00',
    6 => 'Aakjis92',
    7 => 'RabeL_LV',
    8 => 'pending',
  ),
  4 => 
  array (
    0 => 'NeiroN',
    1 => '18',
    2 => 'Saldus',
    3 => 'sunburneD , [q].team , x.cOn ',
    4 => 'ir',
    5 => 'kā kuru dienu !',
    6 => 'edgarito17',
    7 => 'NeiroN',
    8 => 'pending',
  ),
  5 => 
  array (
    0 => 'PluG',
    1 => '14',
    2 => 'Cēsis',
    3 => 'nekas liels nav.... jo parsvara speleju gatherus un mixus..... nu tagad toXc bet ja tiks ujusu tm tad gg vinjiem ^^',
    4 => 'ir',
    5 => 'nu jūnija visu dienu...jo lauzta kaaja...bet parsvara pa dienu no 12-16 un tad vakara no kadiem 18 lidz pat 24',
    6 => 'IIPasi nelietoju',
    7 => 'PluG',
    8 => 'pending',
  ),
  6 => 
  array (
    0 => 'heartbrk',
    1 => '15',
    2 => 'Rīga',
    3 => '^eLeGy^ , ambition , vnk.skilled , cmf , megalix',
    4 => 'ir',
    5 => '10.00 - 0.00',
    6 => 'guilty1963',
    7 => 'heartbrk',
    8 => 'pending',
  ),
  7 => 
  array (
    0 => 'Royal N.',
    1 => '15',
    2 => 'Limbaži, Rīga',
    3 => 'Warriors.lv, GamerX.lv, pārsvarā veidoju savas komandas & labi iznāk, tikai nepareizos cilvēkus atrodu.',
    4 => 'ir',
    5 => 'Ļoti liels katrā ziņā & man vienmēr var uzzvanīt, atnākšu!',
    6 => 'Div1nityy',
    7 => 'Royal',
    8 => 'pending',
  ),
  8 => 
  array (
    0 => 'intensive^',
    1 => '16',
    2 => 'Liepaja',
    3 => '#unlock ',
    4 => 'ir',
    5 => '18',
    6 => 'intensiv54983',
    7 => 'intensive^',
    8 => 'pending',
  ),
  9 => 
  array (
    0 => 'gsT',
    1 => '14',
    2 => 'Riga',
    3 => 'codehunters,hmz',
    4 => 'ir',
    5 => '5 stundas kaa kuru reizi',
    6 => 'resource3',
    7 => '/q gsT',
    8 => 'pending',
  ),
  10 => 
  array (
    0 => 'insector',
    1 => '15',
    2 => 'Dobele',
    3 => 'krutie CodeH',
    4 => 'ir',
    5 => 'varu piecelties kad vaig un palikt cik ilgi vaig ',
    6 => 'insector/spocins',
    7 => 'insector',
    8 => 'pending',
  ),
  11 => 
  array (
    0 => 'soX',
    1 => '14',
    2 => 'Valmiera',
    3 => '<3 gaming - nick',
    4 => 'ir',
    5 => '17:oo- 1:oo ',
    6 => 'Tikai mirC ,bet ja vajag var uztaisiit.',
    7 => 'soX',
    8 => 'pending',
  ),
  12 => 
  array (
    0 => 'endiZor',
    1 => '14',
    2 => 'Jelgava',
    3 => 'exp.tm , elastica , frelance',
    4 => 'ir',
    5 => 'nez.. daudz speleju',
    6 => 'shenster',
    7 => 'endiZor',
    8 => 'pending',
  ),
  13 => 
  array (
    0 => 'omfg',
    1 => '17',
    2 => 'Rīga',
    3 => 'cfg.team utt :/',
    4 => 'ir',
    5 => '10 - 24 ',
    6 => 'jeezus_kristus',
    7 => 'omfg-',
    8 => 'pending',
  ),
  14 => 
  array (
    0 => 'razer',
    1 => '16',
    2 => 'cesis',
    3 => 'canes,megalix,d\'reflex',
    4 => 'ir',
    5 => 'visu dienu...',
    6 => 'nelietoju',
    7 => 'razorNt',
    8 => 'pending',
  ),
  15 => 
  array (
    0 => 'aFTER',
    1 => '14',
    2 => 'Brissele/Riga',
    3 => 'Dazhadi ir bijushi neatceros',
    4 => 'ir',
    5 => 'brivdienas praktiski visu dienu  ka arii nakti a darbdienas no 16 : 40 - 23:00',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  16 => 
  array (
    0 => 'aFTER',
    1 => '14`',
    2 => 'Brissele/Riga',
    3 => 'netcero sdaudz bija',
    4 => 'ir',
    5 => 'brivdienas visu dienu ka ari nakti ja negulju ilgui no rita :D darbdienas no 16: 40 - 23:00  ',
    6 => 'bambucha121 bet Labak Ventrilo',
    7 => 'aFTER',
    8 => 'pending',
  ),
  17 => 
  array (
    0 => 'HeAmgreAT',
    1 => '14',
    2 => 'Balvi',
    3 => 'ELecTriC',
    4 => 'ir',
    5 => 'ja vajag esmu 24/7 :)',
    6 => 'heamgreat',
    7 => 'HeAmgreAT',
    8 => 'pending',
  ),
  18 => 
  array (
    0 => 'crazycover',
    1 => '12',
    2 => 'adazi',
    3 => 'ah nevienu tadu baigi known neatceros ',
    4 => 'ir',
    5 => 'kad vien vajg..',
    6 => 'virzins',
    7 => 'crazycover',
    8 => 'pending',
  ),
  19 => 
  array (
    0 => 'JusT1[D]',
    1 => '15',
    2 => 'Aizkraukle',
    3 => '[45] , Limited.F , HI-MD un veel , bet tos neatceros ',
    4 => 'ir',
    5 => 'Nu nez , kr4 biezhi',
    6 => 'krisits1000',
    7 => 'JusT1[D]',
    8 => 'pending',
  ),
  20 => 
  array (
    0 => 'durcH',
    1 => '14',
    2 => 'Saldus',
    3 => 'GHB -un vel dazi nepopulaari',
    4 => 'ir',
    5 => 'varu kurraa katraa laikaa :)',
    6 => 'durcH-anteer',
    7 => 'durcH',
    8 => 'pending',
  ),
  21 => 
  array (
    0 => 'Journ',
    1 => '13',
    2 => 'Liepaja',
    3 => '[-Gap-] .::gL un vel daudzi visus neaceros',
    4 => 'ir',
    5 => 'vasara parasti no 13:00 lidz 21:00 darbadienas ka sanak',
    6 => 'facker2',
    7 => 'TyTeH',
    8 => 'pending',
  ),
  22 => 
  array (
    0 => 'ravenGeer*',
    1 => '15',
    2 => 'Valmiera',
    3 => 'MAZ BET SKILLOTI',
    4 => 'ir',
    5 => 'kaa kuru reizi !',
    6 => 'ratins007',
    7 => 'ravenger',
    8 => 'pending',
  ),
  23 => 
  array (
    0 => 'Lixon',
    1 => '17',
    2 => 'Riga',
    3 => 'None',
    4 => 'ir',
    5 => '24h',
    6 => 'lixonlv',
    7 => 'Lixon',
    8 => 'pending',
  ),
  24 => 
  array (
    0 => 'nobility',
    1 => '15',
    2 => 'Valmiera ',
    3 => '^eLeGy^ un viss',
    4 => 'ir',
    5 => 'viss ticamak no 9:00-21:00',
    6 => 'nob-nobility',
    7 => 'slieka',
    8 => 'pending',
  ),
  25 => 
  array (
    0 => 'narko',
    1 => '17',
    2 => 'Saulkrasti',
    3 => 'division.elamteray.brutal',
    4 => 'ir',
    5 => '11-18 stabili',
    6 => 'koziksss',
    7 => 'Nark0',
    8 => 'pending',
  ),
  26 => 
  array (
    0 => 'oxbow',
    1 => '17',
    2 => 'Jelgava',
    3 => 'pa vasaru nespeleju, tapec daudzu bijusho klanu nosaukumus esmu aizmirsisis, atceros ka pavasari neighbours klana speleju, tad eng, neatceros nosaukumus komandam kas naca pec tam',
    4 => 'ir',
    5 => 'kad vajag tad esmu',
    6 => 'jackpot-',
    7 => 'oxbow',
    8 => 'pending',
  ),
  27 => 
  array (
    0 => 'KKEE',
    1 => '17',
    2 => 'Rīga',
    3 => 'lv-klans ; [vk] ; codehunters',
    4 => 'ir',
    5 => '15:00 - 00:00',
    6 => 'enzijs',
    7 => 'KKEE',
    8 => 'pending',
  ),
  28 => 
  array (
    0 => 'njasa',
    1 => '15',
    2 => 'Dobele',
    3 => 'PowerPRO igL.',
    4 => 'ir',
    5 => '24/7',
    6 => 'toms_k',
    7 => 'njasa',
    8 => 'pending',
  ),
  29 => 
  array (
    0 => 'insector',
    1 => '15',
    2 => 'Dobele',
    3 => 'nekadi dizie!',
    4 => 'ir',
    5 => 'no cikiem vaig liidz tikiem buushu!',
    6 => 'Raitis zin! spocins/insector',
    7 => 'insector',
    8 => 'pending',
  ),
  30 => 
  array (
    0 => 'Knr',
    1 => '15',
    2 => 'Bauska',
    3 => 'Aizmirsu',
    4 => 'ir',
    5 => 'Dienaa ir kadas 12 h',
    6 => 'nav',
    7 => 'Knr',
    8 => 'pending',
  ),
  31 => 
  array (
    0 => 'MGolts',
    1 => '13',
    2 => 'Liepāja',
    3 => 'Nav',
    4 => 'ir',
    5 => '15:00-23:00',
    6 => 'Mgolts',
    7 => 'MGolts',
    8 => 'pending',
  ),
  32 => 
  array (
    0 => 'aFTER',
    1 => '14',
    2 => 'Riga/Brissele',
    3 => 'dGL, neatceros vairs :(',
    4 => 'ir',
    5 => 'no 15:20 - 23:00',
    6 => 'bambucha121',
    7 => 'aFTER',
    8 => 'pending',
  ),
  33 => 
  array (
    0 => 'Roy',
    1 => '16',
    2 => 'D-pils',
    3 => 'T2D, IcK nav diez ko pazistami klani.. :(',
    4 => 'nav',
    5 => 'Kā kuru dienu',
    6 => 'Visu info kas vajadzīgs lūgums sūtit uz weriks@inbox.lv un par to mikrafonu pašaik nav jo vecais salūza drīz pirkšu jaunu....',
    7 => 'Atvainojos ka nerakstu to kas ir prasīts bet ceru uz atbildi.... [mIRC pašaik nelietoju bet ja vajag tad sedēšu ar niku Roy]',
    8 => 'pending',
  ),
  34 => 
  array (
    0 => 'crazycover',
    1 => '12',
    2 => 'Adazi',
    3 => 'visadi !',
    4 => 'ir',
    5 => 'kad vien vajg',
    6 => 'virzins',
    7 => ' crazycover',
    8 => 'pending',
  ),
  35 => 
  array (
    0 => 'sharpy',
    1 => '13',
    2 => 'Aizkraukle',
    3 => '[LS]',
    4 => 'ir',
    5 => '24/7',
    6 => 'arma6655',
    7 => '',
    8 => 'pending',
  ),
  36 => 
  array (
    0 => 'zerocode',
    1 => '18',
    2 => 'Ogre',
    3 => 'desire',
    4 => 'ir',
    5 => '6 un 7 dien no 21.00 liidz 8 ritaa',
    6 => 'g0ds0ld13r',
    7 => 'zerocode or Chris',
    8 => 'pending',
  ),
  37 => 
  array (
    0 => 'Cubss.normix1 (0wn3d)',
    1 => '11',
    2 => 'Riga',
    3 => 'K.N.D [NwrY] un veel kautkaadi tikai neatceros 10 bija steamaa',
    4 => 'ir',
    5 => 'pa briivdienaam vairaaks anaak bet preciizi nevaru',
    6 => 'normix118',
    7 => '',
    8 => 'pending',
  ),
  38 => 
  array (
    0 => 'Viesulis',
    1 => '12',
    2 => 'Riga',
    3 => 'Apm 4',
    4 => 'ir',
    5 => '14-16, 15-19',
    6 => 'edgarss95',
    7 => 'nav',
    8 => 'pending',
  ),
  39 => 
  array (
    0 => 'Mazais marsietis',
    1 => '10',
    2 => 'Dobele',
    3 => '',
    4 => 'nav',
    5 => '20:00 - 22:00',
    6 => 'nauroo',
    7 => '',
    8 => 'pending',
  ),
  40 => 
  array (
    0 => 'PoweReD^',
    1 => '15',
    2 => 'Rezekne',
    3 => '',
    4 => 'ir',
    5 => 'Pa briivdienaam gandriiz visu dienu :P Bet darbadienaas no 16.00 - 21.00',
    6 => 'PoweReD^',
    7 => 'PoweReD^',
    8 => 'pending',
  ),
  41 => 
  array (
    0 => 'PoweReD^',
    1 => '15',
    2 => 'Rezekne',
    3 => '*bxt ; FouRs ; ',
    4 => 'ir',
    5 => 'Pa briivdienaam gandriiz visu dienu :P Bet darbadienaas no 16.00 - 21.00',
    6 => 'frater.',
    7 => 'PoweReD^',
    8 => 'pending',
  ),
  42 => 
  array (
    0 => 'PoweReD^',
    1 => '15',
    2 => 'Rezekne',
    3 => '*bxt ; FouRs ; ',
    4 => 'ir',
    5 => 'Pa briivdienaam gandriiz visu dienu :P Bet darbadienaas no 16.00 - 21.00',
    6 => 'frater.',
    7 => 'PoweReD^',
    8 => 'pending',
  ),
  43 => 
  array (
    0 => 'LOHS',
    1 => '39',
    2 => 'Mazpisjāņi',
    3 => '[NO-SSC] ^oX',
    4 => 'nav',
    5 => '00:00-24:00',
    6 => 'idiots',
    7 => 'lox',
    8 => 'pending',
  ),
  44 => 
  array (
    0 => 'andress-',
    1 => '21',
    2 => 'Rīga',
    3 => 'Alus Team',
    4 => 'ir',
    5 => '4-7h',
    6 => '.....',
    7 => 'Blue',
    8 => 'pending',
  ),
  45 => 
  array (
    0 => 'apovit',
    1 => '15',
    2 => 'Jurmala',
    3 => 'parlament, un citi draugu klani for fun.',
    4 => 'ir',
    5 => 'oi brivdienas gandriz visu dienu. Darba dienas kadas 5 h [vakaraa]',
    6 => 'tomsnamatevs',
    7 => 'apovit',
    8 => 'pending',
  ),
  46 => 
  array (
    0 => 'PLANTINUM',
    1 => '15',
    2 => 'Riga,Purvciems',
    3 => 'WILD ; GodlyPoision^ ;Sillient.defuse ;game touch ; ',
    4 => 'ir',
    5 => '18-00',
    6 => 'botanik200',
    7 => 'PLANTINUM',
    8 => 'pending',
  ),
  47 => 
  array (
    0 => 'XUI DVE TISJACHI PJATJ',
    1 => '52',
    2 => 'Zimbabva,Africa',
    3 => 'NyP,SK,f-natic,MYM',
    4 => 'ir',
    5 => '24h',
    6 => 'Udwrds52',
    7 => 'XUI',
    8 => 'pending',
  ),
  48 => 
  array (
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => 'ir',
    5 => '',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  49 => 
  array (
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => 'ir',
    5 => '',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  50 => 
  array (
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => 'ir',
    5 => '',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  51 => 
  array (
    0 => 'tulamorE a.K.a insector aceros saucat mani pa mozg 0 tagat mozg 1 :D :D',
    1 => '15',
    2 => 'Dobele',
    3 => 'pz.gaming',
    4 => 'ir',
    5 => 'no 15:50 - visu nakti ja vaig! Ir ari trenina ka njasa tikai vinsh tadus neapmeklee jau kaaadus 4 meeneshus!',
    6 => 'tulamorE/Spocins',
    7 => 'tulamorE',
    8 => 'pending',
  ),
  52 => 
  array (
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => 'ir',
    5 => '',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  53 => 
  array (
    0 => '_4ERVAK_',
    1 => '19',
    2 => 'Riga',
    3 => 'baltgames.lv',
    4 => 'ir',
    5 => '13:00-24:00',
    6 => 'nav',
    7 => '_4ERVAK_',
    8 => 'pending',
  ),
  54 => 
  array (
    0 => 'develop',
    1 => '16',
    2 => 'Cesis',
    3 => 'fosbow, avl , dioxide',
    4 => 'ir',
    5 => 'darb-19:00-24:00 briv- 19:Nenoteikts!',
    6 => 'Neizmantoju!',
    7 => 'develop',
    8 => 'pending',
  ),
  55 => 
  array (
    0 => 'AdVaNcEd^^',
    1 => '14, tulit 15',
    2 => 'Kandava',
    3 => 'Charger(crg.)',
    4 => 'ir',
    5 => 'Ja vaig , varu but kad vajag ...',
    6 => 'Martins R. - AdVaNcEd',
    7 => 'AdVaNcEd',
    8 => 'pending',
  ),
  56 => 
  array (
    0 => 'dLeQeR',
    1 => '17',
    2 => 'Rezekne',
    3 => 'nismo.lv ',
    4 => 'ir',
    5 => '16:00-2300',
    6 => 'turgok3',
    7 => 'dLeQeR',
    8 => 'pending',
  ),
  57 => 
  array (
    0 => 'Magilnik',
    1 => '18',
    2 => 'Daugavpils',
    3 => 'free player',
    4 => 'ir',
    5 => '16-21',
    6 => 'denja1989',
    7 => '',
    8 => 'pending',
  ),
  58 => 
  array (
    0 => 'Magilnik',
    1 => '18',
    2 => 'Daugavpils',
    3 => 'free player',
    4 => 'ir',
    5 => '16-21',
    6 => 'denja1989',
    7 => '',
    8 => 'pending',
  ),
  59 => 
  array (
    0 => 'vip1k',
    1 => '91',
    2 => 'derevushka',
    3 => 'hardcore',
    4 => 'ir',
    5 => '24/7',
    6 => 'ja igraju s wh takzhe kak i vi ',
    7 => 'vozmite plzplzplzplzplzplz',
    8 => 'pending',
  ),
  60 => 
  array (
    0 => 'uruk_hai',
    1 => '17',
    2 => 'Riga',
    3 => 'Kent ,CyberWorld ....',
    4 => 'ir',
    5 => '17:00-22:00',
    6 => 'janjanjan7',
    7 => 'uruk_hai',
    8 => 'pending',
  ),
  61 => 
  array (
    0 => 'evildildo',
    1 => '16',
    2 => 'Valmiera',
    3 => 'nav bijuši, miksus spēlēju.',
    4 => 'ir',
    5 => 'cik ilgi vajaga.',
    6 => 'kexinjs',
    7 => 'evildildo',
    8 => 'pending',
  ),
  62 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  63 => 
  array (
    0 => 'dEksha',
    1 => '14',
    2 => 'Ludza',
    3 => 'woof, hEz',
    4 => 'ir',
    5 => 'no 18:30 - xz',
    6 => 'maartinjs2',
    7 => 'dEksha ( pašlaik stāv bans, 1 dienas laikā ceru noņems, ja kas, rakstāt @ skype par sīkāku informāciju )',
    8 => 'pending',
  ),
  64 => 
  array (
    0 => 'T0TAL',
    1 => '16',
    2 => 'Riga',
    3 => 'division',
    4 => 'ir',
    5 => 'no 12 diena - 1  nakti',
    6 => 'nau',
    7 => 'T0TAL',
    8 => 'pending',
  ),
  65 => 
  array (
    0 => 'Krysts',
    1 => '14',
    2 => 'Jelgava',
    3 => '-',
    4 => 'ir',
    5 => 'kā kuru reizi/ 30-60min',
    6 => 'happy_day_13',
    7 => 'luckyKrysts',
    8 => 'pending',
  ),
  66 => 
  array (
    0 => 'trenky',
    1 => '14',
    2 => 'Preilji',
    3 => '-',
    4 => 'ir',
    5 => 'katru dienu no 12:00 liidz 23:00',
    6 => 'donk221',
    7 => 'trenkijs',
    8 => 'pending',
  ),
  67 => 
  array (
    0 => 'lamers',
    1 => '19',
    2 => 'Ventspils',
    3 => 'nav',
    4 => 'nav',
    5 => 'no 17-22',
    6 => 'nav',
    7 => 'nav',
    8 => 'pending',
  ),
  68 => 
  array (
    0 => 'zerocode',
    1 => '18',
    2 => 'OGRE',
    3 => 'desire, 0manacle, include, conq',
    4 => 'ir',
    5 => '19.00 - 1.00',
    6 => 'g0ds0ld13r',
    7 => 'zerocode, Chris',
    8 => 'pending',
  ),
  69 => 
  array (
    0 => 'macro',
    1 => '19',
    2 => 'Dobele',
    3 => 'Lat}{ost ; gMx',
    4 => 'ir',
    5 => '18:00 - 2:00',
    6 => 'macro_415',
    7 => 'macro',
    8 => 'pending',
  ),
  70 => 
  array (
    0 => 'fds',
    1 => '16',
    2 => 'nvp,nesci,clan.l,EVO,IGNITION,cwm,gaileni ',
    3 => '',
    4 => 'ir',
    5 => '8:00-00:00',
    6 => 'griga500',
    7 => 'Bende[r]',
    8 => 'pending',
  ),
  71 => 
  array (
    0 => 'vikia',
    1 => '10',
    2 => 'talsu rajons',
    3 => 'riga',
    4 => 'nav',
    5 => '16-18',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  72 => 
  array (
    0 => 'soiLe - igL tiimaa biju ar non.effe',
    1 => 'driiz 18',
    2 => 'Liepaja',
    3 => 'igL',
    4 => 'ir',
    5 => 'kad vajag',
    6 => 'rinalds_effect',
    7 => 'soiLe',
    8 => 'pending',
  ),
  73 => 
  array (
    0 => 'Bite biksēs',
    1 => '13',
    2 => 'riga',
    3 => '',
    4 => 'nav',
    5 => '19.40 20.00',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  74 => 
  array (
    0 => 'hortex',
    1 => '20',
    2 => 'Preilji',
    3 => 'w1cked',
    4 => 'ir',
    5 => '6/6',
    6 => 'emilsxx',
    7 => 'hortex',
    8 => 'pending',
  ),
  75 => 
  array (
    0 => 'nets, (knock)',
    1 => '15',
    2 => 'Dobele',
    3 => 'decoder.lv, s4s-|',
    4 => 'ir',
    5 => '08:30 - 22:00,(23:00)',
    6 => 'tomass36',
    7 => 'nets',
    8 => 'pending',
  ),
  76 => 
  array (
    0 => 'exTracT',
    1 => '15',
    2 => 'Ogre',
    3 => 'mheadz,KlowN',
    4 => 'ir',
    5 => '10:00 - 20:00',
    6 => 'grikiits05',
    7 => 'exTracT',
    8 => 'pending',
  ),
  77 => 
  array (
    0 => 'wene',
    1 => '10',
    2 => 'Barcelona',
    3 => 'escalate',
    4 => 'ir',
    5 => '24/7 s 1 goda za kompom',
    6 => 'sasihuj',
    7 => 'wene aka GEJ',
    8 => 'pending',
  ),
  78 => 
  array (
    0 => 'nKYBfQbGEnDKDZAbQi',
    1 => 'xPyyTZeu',
    2 => 'xynMwXsAKAAVY',
    3 => 'CCIYNVxtWc',
    4 => 'ir',
    5 => 'HCMbLrgRvFsThPXVElf',
    6 => 'VYAtOligY',
    7 => 'KBXSGAhWp',
    8 => 'pending',
  ),
  79 => 
  array (
    0 => 'zsJKxxgLfmuF',
    1 => 'oPcpjByoZnNHTeGVxI',
    2 => 'WwNordKII',
    3 => 'dwayCMmLcaICTK',
    4 => 'ir',
    5 => 'vhPGElkQrmnR',
    6 => 'cOSQFqsgFFtHFgua',
    7 => 'AlYGvRcxGxgOoBfeq',
    8 => 'pending',
  ),
  80 => 
  array (
    0 => 'VjFBNpjxRnLQlD',
    1 => 'M27jxQ  <a href="http://xxzlyvnooneo.com/">xxzlyvnooneo</a>, [url=http://nnaejawfdfre.com/]nnaejawfdfre[/url], [link=http://gaxqshjijryu.com/]gaxqshjijryu[/link], http://rawkhghddtdh.com/',
    2 => 'M27jxQ  <a href="http://xxzlyvnooneo.com/">xxzlyvnooneo</a>, [url=http://nnaejawfdfre.com/]nnaejawfdfre[/url], [link=http://gaxqshjijryu.com/]gaxqshjijryu[/link], http://rawkhghddtdh.com/',
    3 => 'LmSRvgHVe',
    4 => 'ir',
    5 => 'PZSyrPdt',
    6 => 'hWjwQCFeKJVTz',
    7 => 'rBWNmOPVyMmIH',
    8 => 'pending',
  ),
  81 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  82 => 
  array (
    0 => 'LGHqvwsuAVOsTfNX',
    1 => 'nTvqapDmfeESM',
    2 => 'NGiHidPGmXGCUeKFYbR',
    3 => 'CLQiOLdl',
    4 => 'ir',
    5 => 'dGarBfSuY',
    6 => 'bilyoKIQjQ',
    7 => 'MKNoLscCOlZ',
    8 => 'pending',
  ),
  83 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  84 => 
  array (
    0 => 'BhDufxrGqYI',
    1 => 'tTQjpeGCvvNOgIYH',
    2 => 'hcLKtxUNLvq',
    3 => 'qOAihCJVACqux',
    4 => 'ir',
    5 => 'ZoltrqfaodBGBKCXBaB',
    6 => 'kBOafOFsEtpiFoc',
    7 => 'HSwIiYGDJEJ',
    8 => 'pending',
  ),
  85 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  86 => 
  array (
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => 'ir',
    5 => '',
    6 => '',
    7 => '',
    8 => 'pending',
  ),
  87 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  88 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  89 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  90 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  91 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  92 => 
  array (
    0 => 'luidji',
    1 => 'MJjhCZZHe',
    2 => 'UrGILpAY',
    3 => 'beSJLhyKgsu',
    4 => 'ir',
    5 => 'SeaVkMTfiZcbdDFc',
    6 => 'mbkNVHcizKoWjrwlh',
    7 => 'uxclhdGHjU',
    8 => 'pending',
  ),
  93 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  94 => 
  array (
    0 => 'MFulwdEzTGQz',
    1 => 'iVEpulLzJBdS',
    2 => 'DwWmCiXLnnnfJGwfM',
    3 => 'ALHPvSOAD',
    4 => 'ir',
    5 => 'cKktZbvj',
    6 => 'qUrPgCKEvqxyjiVqvVd',
    7 => 'GiVJkySAfDfGzT',
    8 => 'pending',
  ),
  95 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  96 => 
  array (
    0 => 'Bradley',
    1 => 'nGyxxdKC',
    2 => 'lNbeMDgsaKzyMHw',
    3 => 'dtCrllolsJYbwRb',
    4 => 'ir',
    5 => 'gGRfPxMswxXpQWBEkG',
    6 => 'BFijfRAzVp',
    7 => 'eOWxyWjddYhyBgL',
    8 => 'pending',
  ),
  97 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  98 => 
  array (
    0 => 'Bradley',
    1 => 'YdnhKdBzT',
    2 => 'xhNyUwUXam',
    3 => 'UdETqHDSbhhsOw',
    4 => 'ir',
    5 => 'EYlOUDIjO',
    6 => 'BzIRvTzQxrIYFLSczyL',
    7 => 'ypcJpLOVMyWL',
    8 => 'pending',
  ),
  99 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  100 => 
  array (
    0 => 'Bradley',
    1 => 'SOheVOjLDqukZHWDwdX',
    2 => 'AWeVRxHghFx',
    3 => 'QBNYIzQEqzl',
    4 => 'ir',
    5 => 'rHuUnsisbyjH',
    6 => 'ubkNMbyodShUDQ',
    7 => 'UbrOXNXdAmOxheaQ',
    8 => 'pending',
  ),
  101 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  102 => 
  array (
    0 => 'Mark',
    1 => 'vTOMfGCdNLrnfT',
    2 => 'qvXsoNeRnXdrCRo',
    3 => 'nvnvOuCsxvXBQvdcoBE',
    4 => 'ir',
    5 => 'UbkMKpnQIheQngQbYn',
    6 => 'bSYqfxBDIE',
    7 => 'lDmMhhViuWuUqwn',
    8 => 'pending',
  ),
  103 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  104 => 
  array (
    0 => 'Mark',
    1 => 'gmTOGDyxoYMdk',
    2 => 'ZsbfZFjhgEcERXZI',
    3 => 'fRbMlCqJClYqepZd',
    4 => 'ir',
    5 => 'xixQFJlZdn',
    6 => 'USnPYmRcOEDxb',
    7 => 'YusMKGEwqfwWXS',
    8 => 'pending',
  ),
  105 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  106 => 
  array (
    0 => 'Mark',
    1 => 'nQUdBnimSOBmDDjcJ',
    2 => 'KgLRnQFXgSh',
    3 => 'PTfOEaJbwx',
    4 => 'ir',
    5 => 'VpRzfyRZR',
    6 => 'lCGQHJCbRuRnlEnEBD',
    7 => 'JZahmaYRBLq',
    8 => 'pending',
  ),
  107 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  108 => 
  array (
    0 => 'Mark',
    1 => 'dJozjLyzY',
    2 => 'occYEWVIqgMeQw',
    3 => 'GnYstvgEXD',
    4 => 'ir',
    5 => 'fvZOAWgMizwPK',
    6 => 'CXUTsVowDUz',
    7 => 'ehukJpAhzOHfxWVt',
    8 => 'pending',
  ),
  109 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  110 => 
  array (
    0 => 'Mark',
    1 => 'WQjYVoEhlqhIZZgd',
    2 => 'uWKivuFfVdPknj',
    3 => 'WXUwcrWTB',
    4 => 'ir',
    5 => 'JCCIwEuFTEdf',
    6 => 'UBxATdLReI',
    7 => 'YDZvnBEuAedBTOkfRDx',
    8 => 'pending',
  ),
  111 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  112 => 
  array (
    0 => 'Mark',
    1 => 'NDsgvqKkblRaKD',
    2 => 'UGgqcYhYsnl',
    3 => 'DxoZNHxwbFgdd',
    4 => 'ir',
    5 => 'THVxOhYWTRPPLgg',
    6 => 'JZbprZboimmOAsJ',
    7 => 'PkZzsdswTHH',
    8 => 'pending',
  ),
  113 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  114 => 
  array (
    0 => 'chaba',
    1 => 'ddlBprwbonIfqW',
    2 => 'CBSDtTrNezMq',
    3 => 'akpWUCISJLlCa',
    4 => 'ir',
    5 => 'FXTYVmOhjfvriKlsqsL',
    6 => 'KUSrJYRfocDAqJX',
    7 => 'GLzqxmEuBEfYmzrL',
    8 => 'pending',
  ),
  115 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  116 => 
  array (
    0 => 'matt',
    1 => 'pPsHPBnAPetYRbHOfm',
    2 => 'xvwMqSqH',
    3 => 'mpMuNOSDERZH',
    4 => 'ir',
    5 => 'ozrPlFcWDnkdNneCp',
    6 => 'CbifHzhMjBt',
    7 => 'PCBUufRWQqBTmRzYE',
    8 => 'pending',
  ),
  117 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
  118 => 
  array (
    0 => 'Mark',
    1 => 'pWrDhrTqbJpRWRXSymW',
    2 => 'pHtOGcqHpsInZp',
    3 => 'nAyXVAvUwcFBPUHG',
    4 => 'ir',
    5 => 'VHpmgHJwPVXRc',
    6 => 'MDchlXjvGfuhmsMLTit',
    7 => 'mIDdGVIEzcWY',
    8 => 'pending',
  ),
  119 => 
  array (
    0 => NULL,
    1 => NULL,
    2 => NULL,
    3 => NULL,
    4 => NULL,
    5 => NULL,
    6 => NULL,
    7 => NULL,
    8 => 'pending',
  ),
); ?>